from selenium import webdriver
options = webdriver.ChromeOptions()
options.add_argument('--no-sandbox')
options.add_argument('--window-size=1420,1080')
options.add_argument('--headless')
options.add_argument('--disable-gpu')
options.add_argument("--lang=fr")
driver = webdriver.Chrome(options=options)
driver.get("http://perdu.com")
driver.save_screenshot("screenshot.png")
body = driver.find_element_by_tag_name("body")
h1 = body.find_element_by_tag_name("h1")
h2 = body.find_element_by_tag_name("h2")
assert(h1.text == "Perdu sur l'Internet ?")
assert(h2.text == "Pas de panique, on va vous aider")
print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
print("~ This selenium test is successful ! ~")
print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")